### ISSUE TITLE
Need a bit of help

### ISSUE THREAD

**Issue by Swordfisherman** [petrbroz/forge-basic-app#1]
Hello Mr Broz,

I made a small mistake on this project's Live demo. This is why I would like to ask for your help. Thanks in advance for your respone.

Regards,
Swordfish

**Comment by petrbroz** [comment]
Hi @Swordfisherman, what exactly do you need help with?

**Comment by Swordfisherman** [comment]
@petrbroz Thank you for responding. 

I accidentally uploaded the wrong files into the Online demo of this app and wanted to ask if you could maybe remove them from the bucket.

The files in question are: "testen.obj" and "1725.017.000.gltf".

**Comment by petrbroz** [comment]
Sure, just removed these. I see there are many experimental design that have been uploaded by the site visitors, many of them not even working, so I'll need to do a wider cleanup.
